name: One Flame in the Fire
favicon: null
layout_spectrum: 0.73413
typography_spectrum: 0.72013
title: 1Flame
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2f48'
    - '#fcfcfc'
    - '#457aa8'
    - '#c8cbc6'
    - '#ff8f59'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
