name: One Flame in the Fire
favicon: null
layout_spectrum: 0.43072320194914937
typography_spectrum: 0.72013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2f48'
    - '#fcfcfc'
    - '#457aa8'
    - '#c8cbc6'
    - '#ff8f59'
  brandStrength: 0.375
  lightness: 0.24530377006158233
  saturation: 0.3364353042561561
  rhythmicContrast: 0.5599539885297418
purpose: []
