name: One Flame in the Fire
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2f48'
    - '#fcfcfc'
    - '#457aa8'
    - '#c8cbc6'
    - '#ff8f59'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
